## Numpy Array and Basics


In [2]:
import numpy as np

### Creating Array From List

In [3]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [4]:
b=np.array([[1,2,3,4],[6,7,8,9]])
print(b)

[[1 2 3 4]
 [6 7 8 9]]


### List Vs Numpy Array

In [10]:
import time
my_list=[1,2,3,4]
print("Python List Multiplication :",my_list*2)

num_array=np.array([1,2,3,4])
print("Python Numpy Array Multiplication :",num_array*2)

start=time.time()
py_list=[i*2 for i in range(100000)]
print("List Operation time:",time.time()-start)

start=time.time()
arr=np.arange(100000)*2
print("Numpy Operation Time :",time.time()-start)


Python List Multiplication : [1, 2, 3, 4, 1, 2, 3, 4]
Python Numpy Array Multiplication : [2 4 6 8]
List Operation time: 0.008929729461669922
Numpy Operation Time : 0.0003821849822998047


### Creating Arrays From Scratch


In [6]:
zero=np.zeros((4,4))
print(zero)
ones=np.ones((2,3))
print(ones)
full=np.full((2,2),7)
print(full)
random=np.random.random((2,3))
print(random)
sequence=np.arange(0,10,2) # last stop step
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.06532847 0.31256661 0.8050033 ]
 [0.36061476 0.1200236  0.4814339 ]]
[0 2 4 6 8]


### Vector Matrices and Tensor

In [19]:
vector=np.array([1,2,3,4,5])
print(vector)
matrix=np.array([[2,3,4],[2,32,3]])
print(matrix)
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[1 2 3 4 5]
[[ 2  3  4]
 [ 2 32  3]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [20]:
my_array=np.array([[1,2,3],
                   [4,5,6]])
shape=my_array.shape
dimension=my_array.ndim
size=my_array.size
Dtype=my_array.dtype
print("Shape :",shape)
print("Dimension :",dimension)
print("Size :",size)
print("Data Type :",Dtype)


Shape : (2, 3)
Dimension : 2
Size : 6
Data Type : int64


### Array Reshaping 

In [25]:
arr1=np.arange(12)
print("Original Array :",arr1)
Reshaped=arr1.reshape((3,4))
print("Reshaped Array :",Reshaped)
flat=Reshaped.flatten()
print("Faltened Array :",flat)
raveled=Reshaped.ravel() # returns veiw instead of copy
print("Raveled Array :",raveled)

# Tranpose
transpose=Reshaped.T;
print("Transposed Array :",transpose)



Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Faltened Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Indexing And Silicing

In [ ]:
arr12=np.arange(19)
print("Basic Slicing :",arr12[2:7])
print("With Step :",arr12[1:8:2])
print("Negative Indexing :",arr12[-3])
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Specific Element :",arr_2d[1,2])
print("Specific Row :",arr_2d[1])
print("Specific Column :",arr_2d[:,1])


Basic Slicing : [2 3 4 5 6]
With Step : [1 3 5 7]
Negative Indexing : 16
Specific Element : 6
Specific Row : [4 5 6]
Specific Column : [2 5 8]


### Sorting 

In [37]:
unsorted=np.array([3,1,4,0,5,7,6,10])
print("Sorted Array :",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D Array by Column :",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D Array by Row :",np.sort(arr_2d_unsorted,axis=1))

Sorted Array : [ 0  1  3  4  5  6  7 10]
Sorted 2D Array by Column : [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by Row : [[1 3]
 [1 2]
 [2 3]]


### Filtering 

In [ ]:
numbers=np.arange(11)
even_number=numbers[numbers%2 ==0] # inside we condition of filtering
print("Even Numbers :",even_number)

Even Numbers : [ 0  2  4  6  8 10]


### Filter with Mask

In [39]:
mask=numbers>5
print("Numbers greater than 5 :",numbers[mask])

Numbers greater than 5 : [ 6  7  8  9 10]


### Fancy Index vs np.where()

In [42]:
indices=[0,2,4]
print(numbers[indices])
where_result=np.where(numbers>5)
print(where_result)
print("Np Where :",numbers[where_result])

[0 2 4]
(array([ 6,  7,  8,  9, 10]),)
Np Where : [ 6  7  8  9 10]


In [46]:
condition_array=np.where(numbers>5,"True","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'False' 'True' 'True' 'True'
 'True' 'True']


### Adding and Removing Data 

In [54]:
a=np.array([1,2,3])
b=np.array([4,5,6])
combined=np.concatenate((a,b))
print(combined)

arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("Deleted Array :",deleted)

[1 2 3 4 5 6]
Deleted Array : [1 2 4 5]


### Array Compatibility 

In [ ]:
c=np.array([1,2,3])
d=np.array([4,5,6])
e=np.array([7,8,9])
print("Comapatibility Shapes :",c.shape==d.shape)

# column adding and Row Adding
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
print(original)
with_new_row=np.vstack((original,new_row))
print(with_new_row)
new_column=np.array([[7],[8]])
with_new_col=np.hstack((original,new_column))
print(with_new_col)


Comapatibility Shapes : True
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
